python -W ignore run_simulation.py --r_test 0.1 --p 20 &
python -W ignore run_simulation.py --r_test 0.2 --p 20 &
python -W ignore run_simulation.py --r_test 0.3 --p 20 &
python -W ignore run_simulation.py --r_test 0.4 --p 20 &
python -W ignore run_simulation.py --r_test 0.5 --p 20 &
python -W ignore run_simulation.py --r_test 0.6 --p 20 &
python -W ignore run_simulation.py --r_test 0.7 --p 20 &
python -W ignore run_simulation.py --r_test 0.8 --p 20 &
python -W ignore run_simulation.py --r_test 0.9 --p 20 & 
python -W ignore run_simulation.py --r_test 0.1 --p 80 &
python -W ignore run_simulation.py --r_test 0.2 --p 80 &
python -W ignore run_simulation.py --r_test 0.3 --p 80 &
python -W ignore run_simulation.py --r_test 0.4 --p 80 &
python -W ignore run_simulation.py --r_test 0.5 --p 80 &
python -W ignore run_simulation.py --r_test 0.6 --p 80 &
python -W ignore run_simulation.py --r_test 0.7 --p 80 &
python -W ignore run_simulation.py --r_test 0.8 --p 80 &
python -W ignore run_simulation.py --r_test 0.9 --p 80 & 
